version: "3.3"

services:
  local-development-db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/local-development-data
    ports:
      - "5555:5432"
      #Use port 5555 to connect externally
    volumes:
      - local-development-pg-volume:/var/lib/postgresql/local-development-data:rw

volumes:
  local-development-pg-volume:
    external: true
#run following for the first time before starting the docker, this will make db persistent
# run docker volume create --name=local-development-pg-volume

