version: "3.3"

services:
  local-test-db:
    image: postgres:14.1-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_NAME: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5556:5432"
      #Use port 5556 to connect externally
